version: "3.1"
services:
  db:
    build:
      context: .
      dockerfile: db.Containerfile
    restart: always
    user: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata:
