[tool.poetry]
name = "Tomography Archival Management Systen"
version = "0.1.0"
description = ""
license = "MIT"
authors = [
    "Tom Kusonsuphanimit <tom.kusonsuphanimit@manchester.ac.uk>"
]
readme = "README.md"
repository = "https://github.com/UoM-NXCT/TAMS"

[tool.poetry.urls]
"NXCT homepage" = "https://nxct.ac.uk/"
"The University of Manchester homepage" = "https://www.manchester.ac.uk/"

[tool.poetry.dependencies]
python = "<3.12,^3.10,"
PySide6 = "^6.4.0"
tomli = "^2.0.1"
psycopg = {extras = ["binary"], version = "^3.1.3"}
tomli-w = "^1.0.0"
pylint = "^2.15.5"

[tool.poetry.group.dev.dependencies]
black = {extras = ["d"], version = "^22.10.0"}
pylint = "^2.15.5"
pytest = "^7.1.3"
isort = "^5.10.1"
mypy = "^0.982"
coverage = "^6.5.0"
sqlfluff = "^1.4.1"
pyinstaller = "^5.6.2"

[tool.black]
line-length = 88
target-version = ["py310", "py311"]

[tool.pylint."MESSAGES CONTROL"]
max-line-length = 88
# Qt uses camelCase for its methods; tell pylint to ignore invalid-name
disable = """
    invalid-name
"""

[tool.isort]
profile = "black"

[tool.sqlfluff.core]
dialect = "postgres"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
