# -*- coding: utf-8 -*-
"""Initialiser model

Contains a model that initialises the database. For use when first creating a database.
"""

import logging
from datetime import date

from client.db import Database


class DatabaseInitialiser(Database):
    """Initialise a database."""

    def __init__(
        self, connection_string: str, populate_with_fake_data: bool = False
    ) -> None:
        """Initialise self then populate database."""
        super().__init__(connection_string)
        self.init_db()
        if populate_with_fake_data:
            # Warning: this deletes all data that already exists in tables!
            self.populate_with_fake_data()

    def init_db(self):
        """Create database tables."""
        logging.info("Creating database tables")
        self.create_user_table()
        self.create_project_table()
        self.create_instrument_table()
        self.create_project_user_table()

        self.create_project_instrument_table()
        self.create_sample_table()
        self.create_scan_table()
        self.create_scan_sample_table()

    def create_user_table(self) -> None:
        """Create user table in database."""
        self.exec(
            """
        create table "user"
        (
            user_id integer generated by default as identity
            constraint user_pk primary key,
            first_name text not null,
            last_name text not null,
            email_address text
        );

        comment on column "user".email_address is
        'Treat emails as case-insensitive when performing comparisons.';

        alter table "user" owner to postgres;
        """
        )

    def create_project_table(self) -> None:
        """Create project table in database."""
        self.exec(
            """
        create table project
        (
            project_id integer generated by default as identity
            constraint project_pk primary key,
            title text,
            project_type text,
            summary text,
            keyword text,
            start_date date,
            end_date date,
            directory_path text
        );

        comment on column project.directory_path is
        'Note: is there a better way of storing a directory location?';

        alter table project owner to postgres;
        """
        )

    def create_instrument_table(self) -> None:
        """Create instrument table in database."""
        self.exec(
            """
        create table instrument
        (
            instrument_id integer generated by default as identity
            constraint instrument_pk primary key,
            name text,
            status text
        );

        alter table instrument owner to postgres;
        """
        )

    def create_project_user_table(self) -> None:
        """Create project-user table for a many-to-many relationship in database."""
        self.exec(
            """
        create table project_user
        (
            user_id integer not null
            constraint project_user_user_null_fk references "user",
            project_id integer not null
            constraint project_user_project_null_fk references project
        );

        alter table project_user owner to postgres;
        """
        )

    def create_project_instrument_table(self) -> None:
        """Create project-instrument table for a many-to-many relationship in database."""
        self.exec(
            """
        create table project_instrument
        (
            instrument_id integer not null
            constraint project_instrument_instrument_null_fk references instrument,
            project_id integer not null
            constraint project_instrument_project_null_fk references project
        );

        alter table project_instrument owner to postgres;
        """
        )

    def create_sample_table(self) -> None:
        """Create sample table in database."""
        self.exec(
            """
        create table sample
        (
            sample_id integer generated by default as identity
            constraint sample_pk primary key,
            name text,
            size numeric,
            material text,
            confidentiality boolean default false not null
        );

        alter table sample owner to postgres;
        """
        )

    def create_scan_table(self) -> None:
        """Create scan table in database."""
        self.exec(
            """
        create table scan
        (
            scan_id integer generated by default as identity
            constraint scan_pk primary key,
            voltage numeric,
            amperage numeric,
            exposure numeric,
            projections integer,
            voxel_size numeric,
            filter_thick text,
            filter_material text,
            projection_example bytea,
            source_sample_distance real,
            sample_detector_distance real,
            lens_type text,
            project_id integer not null
            constraint scan_project_null_fk references project
        );

        comment on column scan.voltage is
        'Note: Amin says this should be an integer, but is that correct?';

        comment on column scan.amperage is
        'Ditto';

        comment on column scan.exposure is
        'Ditto';

        alter table scan owner to postgres;
        """
        )

    def create_scan_sample_table(self) -> None:
        """Create scan-sample table for a many-to-many relationship in database."""
        self.exec(
            """
        create table scan_sample
        (
            sample_id integer not null
            constraint scan_sample___fk references sample,
            scan_id integer not null
            constraint scan_sample_scan_null_fk references scan
        );

        alter table scan_sample owner to postgres;
        """
        )

    def populate_with_fake_data(self) -> None:
        """Populate the tables with fake data. This should only be used in development."""

        # Fake instruments
        self.exec("delete from instrument;")
        self.exec(
            "insert into instrument (name, status) values (%s, %s)",
            ("Nikon", "Utterly destroyed"),
        )
        self.exec(
            "insert into instrument (name, status) values (%s, %s)",
            ("Zeiss", "Working fine"),
        )
        self.exec(
            "insert into instrument (name, status) values (%s, %s)",
            ("Rapiscan", "Amin spilt coffee on it"),
        )
        # Fake samples
        self.exec("delete from sample;")
        self.exec(
            "insert into sample (name, size, material, confidentiality) values (%s, %s, %s, %s);",
            ("Mug", 15, "Ceramic", False),
        )
        self.exec(
            "insert into sample (name, size, material, confidentiality) values (%s, %s, %s, %s);",
            ("Bucket (no head)", 50, "Steel", True),
        )
        self.exec(
            "insert into sample (name, size, material, confidentiality) values (%s, %s, %s, %s);",
            ("Deadpool", 25, "Paper", False),
        )
        self.exec(
            "insert into sample (name, size, material, confidentiality) values (%s, %s, %s, %s);",
            ("Pocket watch", 5, "Gold", False),
        )
        # Fake users
        self.exec('delete from "user";')
        self.exec(
            'insert into "user" (first_name, last_name, email_address) values (%s, %s, %s);',
            ("Amin", "Garbout", "amin.garbout@manchester.ac.uk"),
        )
        self.exec(
            'insert into "user" (first_name, last_name, email_address) values (%s, %s, %s);',
            ("Elizabeth", "Evans", "elizabeth.evans-5@manchester.ac.uk"),
        )
        self.exec(
            'insert into "user" (first_name, last_name, email_address) values (%s, %s, %s);',
            ("Tristan", "Lowe", "Tristan.Lowe@manchester.ac.uk"),
        )
        # Fake projects
        self.exec("delete from project")
        self.exec(
            "insert into project (title, project_type, summary, keyword, start_date, end_date, directory_path) values (%s, %s, %s, %s, %s, %s, %s);",
            (
                "The caffeine-resistance of XCT machines.",
                "Lunch break",
                "Can imaging equipment drink coffee? There is only one way to find out!",
                "coffee",
                date(2022, 10, 2),
                date(2022, 10, 3),
                "~/documents/coffee/",
            ),
        )
        self.exec(
            "insert into project (title, project_type, summary, keyword, start_date, end_date, directory_path) values (%s, %s, %s, %s, %s, %s, %s);",
            (
                "Analysis of a bucket with nothing inside",
                "Detective work",
                "We are very confident there is nothing in this bucket, but we should check first.",
                "bucket",
                date(2022, 9, 15),
                date(2022, 10, 1),
                "~/documents/bucket/",
            ),
        )

        self.exec(
            "insert into project (title, project_type, summary, keyword, start_date, end_date, directory_path) values (%s, %s, %s, %s, %s, %s, %s);",
            (
                "Non-destructive pinata party",
                "Birthday",
                "Do sweets expire?",
                "deadpool",
                date(2022, 10, 30),
                date(2022, 10, 31),
                "~/documents/deadpool/",
            ),
        )

        self.exec(
            "insert into project (title, project_type, summary, keyword, start_date, end_date, directory_path) values (%s, %s, %s, %s, %s, %s, %s);",
            (
                "Titanic 2",
                "Research",
                "Directory James Cameron sees money to be made here.",
                "watch",
                date(2022, 9, 29),
                date(2023, 1, 31),
                "~/documents/titanic-watch/",
            ),
        )

        # Fake project-instrument links
        self.exec("delete from project_instrument")
        self.exec(
            """
            insert into project_instrument (instrument_id, project_id) values
                (
                    (select instrument_id from instrument where name = 'Rapiscan'),
                    (select project_id from project where title = 'The caffeine-resistance of XCT machines.')
                    
                ),
                (
                    (select instrument_id from instrument where name = 'Nikon'),
                    (select project_id from project where title = 'Analysis of a bucket with nothing inside')
                    
                ),
                (
                    (select instrument_id from instrument where name = 'Zeiss'),
                    (select project_id from project where title = 'Non-destructive pinata party')
                    
                ),
                (
                    (select instrument_id from instrument where name = 'Zeiss'),
                    (select project_id from project where title = 'Titanic 2')
                    
                );
        """
        )

        # Fake project-user links
        self.exec("delete from project_user")
        self.exec(
            """
            insert into project_user (user_id, project_id) values
                (
                    (select user_id from "user" where first_name = 'Amin'),
                    (select project_id from project where title = 'The caffeine-resistance of XCT machines.')
    
                ),
                (
                    (select user_id from "user" where first_name = 'Elizabeth'),
                    (select project_id from project where title = 'Analysis of a bucket with nothing inside')
    
                ),
                (
                    (select user_id from "user" where first_name = 'Tristan'),
                    (select project_id from project where title = 'Non-destructive pinata party')
    
                ),
                (
                    (select user_id from "user" where first_name = 'Elizabeth'),
                    (select project_id from project where title = 'Titanic 2')
    
                );
            """
        )

        # Fake scan-project links
        self.exec("delete from scan;")
        self.exec(
            "insert into scan (voltage, amperage, exposure, projections, voxel_size, filter_thick, filter_material, source_sample_distance, sample_detector_distance, lens_type, project_id) values (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,(select project_id from project where title = 'The caffeine-resistance of XCT machines.'));",
            (1, 1, 1, 3716, 1, "Very thick", "Glass?", 0.3, 0.6, "Big"),
        )
        self.exec(
            "insert into scan (voltage, amperage, exposure, projections, voxel_size, filter_thick, filter_material, source_sample_distance, sample_detector_distance, lens_type, project_id) values (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,(select project_id from project where title = 'Analysis of a bucket with nothing inside'));",
            (1, 2, 3, 3716, 4, "Very thick", "Glass?", 0.3, 0.5, "Medium"),
        )
        self.exec(
            "insert into scan (voltage, amperage, exposure, projections, voxel_size, filter_thick, filter_material, source_sample_distance, sample_detector_distance, lens_type, project_id) values (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,(select project_id from project where title = 'Non-destructive pinata party'));",
            (2, 1, 1, 3716, 1, "Very thin", "Glass?", 0.4, 0.5, "Small"),
        )
        self.exec(
            "insert into scan (voltage, amperage, exposure, projections, voxel_size, filter_thick, filter_material, source_sample_distance, sample_detector_distance, lens_type, project_id) values (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,(select project_id from project where title = 'Titanic 2'));",
            (3, 2, 3, 3716, 1, "Very thick", "Glass?", 0.3, 0.5, "Big"),
        )

        # Fake scan-sample links
        self.exec("delete from scan_sample;")
        self.exec(
            """
                        insert into scan_sample (sample_id, scan_id) values
                            (
                                (select sample_id from sample where name = 'Mug'),
                                (select scan_id from scan where project_id = (select project_id from project where title = 'The caffeine-resistance of XCT machines.'))
    
                            ),
                            (
                                (select sample_id from sample where name = 'Bucket (no head)'),
                                (select scan_id from scan where project_id = (select project_id from project where title = 'Analysis of a bucket with nothing inside'))
    
                            ),
                            (
                                (select sample_id from sample where name = 'Deadpool'),
                                (select scan_id from scan where project_id = (select project_id from project where title = 'Non-destructive pinata party'))
    
                            ),
                            (
                                (select sample_id from sample where name = 'Pocket watch'),
                                (select scan_id from scan where project_id = (select project_id from project where title = 'Titanic 2'))
    
                            );
                    """
        )


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    # When running postgres via Docker, localhost doesn't map to 127.0.0.1; WTF??
    CONFIG = "host=127.0.0.1 port=5432 dbname=tams user=postgres password=postgres"
    with DatabaseInitialiser(CONFIG) as db:
        pass
    print("Database initialised")
