# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# TODO: Add mypy checking when PySide6 has better type support
# https://github.com/UoM-NXCT/TAMS/issues/5

name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Check formatting
        run: |
          poetry run flake8 . --count --show-source --statistics
          poetry run black . --check
          poetry run ssort . --check
          poetry run sqlfluff lint .
